Repository ironcore-dev/metal, pull requests merged in 2024-03, with the labels that each got.

#464 Bump ipam to `v0.1.1`, oob to `v0.5.1`
  go.mod
  go.sum
  pkg/switches/helpers_test.go
Labels: enhancement, size/L

#465 Fix/fix actions
  .github/workflows/golangci-lint.yml
  .github/workflows/publish-docker-metal-provider.yml
  .github/workflows/publish-docker.yml
  .github/workflows/release-drafter.yml
  .github/workflows/size-label.yml
  .github/workflows/test.yml
  Dockerfile
  hack/setup-git-redirect.sh
  metal-provider/Dockerfile
Labels: bug, size/M

#469 Move metal-provider to its own repo
  .github/dependabot.yml
  .github/workflows/publish-docker-metal-provider.yml
  .reuse/dep5
  metal-provider/Dockerfile
  metal-provider/config/default/kustomization.yaml
  metal-provider/config/default/manager_auth_proxy_patch.yaml
  metal-provider/config/manager/kustomization.yaml
  metal-provider/config/manager/manager.yaml
  metal-provider/config/rbac/auth_proxy_client_clusterrole.yaml
  metal-provider/config/rbac/auth_proxy_role.yaml
  metal-provider/config/rbac/auth_proxy_role_binding.yaml
  metal-provider/config/rbac/auth_proxy_service.yaml
  metal-provider/config/rbac/kustomization.yaml
  metal-provider/config/rbac/leader_election_role.yaml
  metal-provider/config/rbac/leader_election_role_binding.yaml
  metal-provider/config/rbac/role.yaml
  metal-provider/config/rbac/role_binding.yaml
  metal-provider/config/rbac/service_account.yaml
  metal-provider/internal/log/log.go
  metal-provider/internal/patch/patch.go
  metal-provider/internal/unix/unix.go
  metal-provider/main.go
  metal-provider/servers/grpc_server.go
  metal-provider/tools.go
Labels: size/XXL

#474 Switch to new IPAM API `ipam.metal.ironcore.dev`
  apis/metal/v1alpha4/switchconfig_webhook_test.go
  config/rbac/role.yaml
  config/samples/ipam_v1alpha1_subnet.yaml
  config/samples/switch_v1beta1_switch.yaml
  config/samples/switch_v1beta1_switchconfig.yaml
  config/samples/testdata/standalone-switches-v4.yaml
  config/samples/testdata/switch-ranges-v4.yaml
  config/samples/testdata/switch-ranges-v6.yaml
  config/samples/testdata/switches-v4.yaml
  config/samples/testdata/switches-v6.yaml
  config/samples/testdata/underlay-network.yaml
  controllers/onboarding/inventory.go
  controllers/switch/ipam_controller.go
  docs/usage/loopbacks.md
  docs/usage/switch.md
  go.mod
  go.sum
  pkg/constants/switch.go
  pkg/switches/helpers_test.go
  test_samples/switch/networks/overlay-network.yaml
  test_samples/switch/subnets/carrier-v4.yaml
  test_samples/switch/subnets/carrier-v6.yaml
  test_samples/switch/subnets/loopbacks-v4.yaml
  test_samples/switch/subnets/loopbacks-v6.yaml
  test_samples/switch/switch_configs/leafs-config.yaml
  test_samples/switch/switch_configs/spines-config.yaml
  test_samples/switch/switch_ipam_objects/loopbacks/leaf-1.loopback-v4.yaml
  test_samples/switch/switch_ipam_objects/loopbacks/leaf-1.loopback-v6.yaml
  test_samples/switch/switch_ipam_objects/loopbacks/leaf-2.loopback-v4.yaml
  test_samples/switch/switch_ipam_objects/loopbacks/leaf-2.loopback-v6.yaml
  test_samples/switch/switch_ipam_objects/loopbacks/spine-1.loopback-v4.yaml
  test_samples/switch/switch_ipam_objects/loopbacks/spine-1.loopback-v6.yaml
  test_samples/switch/switch_ipam_objects/loopbacks/spine-2.loopback-v4.yaml
  test_samples/switch/switch_ipam_objects/loopbacks/spine-2.loopback-v6.yaml
  test_samples/switch/switch_ipam_objects/subnets/00-spine-1.subnet-v4.yaml
  test_samples/switch/switch_ipam_objects/subnets/00-spine-1.subnet-v6.yaml
  test_samples/switch/switch_ipam_objects/subnets/01-spine-2.subnet-v4.yaml
  test_samples/switch/switch_ipam_objects/subnets/01-spine-2.subnet-v6.yaml
  test_samples/switch/switch_ipam_objects/subnets/02-leaf-1.subnet-v4.yaml
  test_samples/switch/switch_ipam_objects/subnets/02-leaf-1.subnet-v6.yaml
  test_samples/switch/switch_ipam_objects/subnets/03-leaf-2.subnet-v4.yaml
  test_samples/switch/switch_ipam_objects/subnets/03-leaf-2.subnet-v6.yaml
Labels: documentation, enhancement, controllers, size/L
