Repository ironcore-dev/metal, pull requests merged in 2024-06, with the labels that each got.

#90 Implement machine control
  api/v1alpha1/machine_types.go
  api/v1alpha1/oob_types.go
  client/applyconfiguration/internal/internal.go
  client/openapi/zz_generated.openapi.go
  cmd/main.go
  config/crd/bases/metal.ironcore.dev_machineclaims.yaml
  config/crd/bases/metal.ironcore.dev_machines.yaml
  config/crd/bases/metal.ironcore.dev_oobs.yaml
  internal/bmc/bmc.go
  internal/bmc/fake.go
  internal/bmc/ipmi.go
  internal/bmc/redfish.go
  internal/controller/oob_controller.go
  internal/controller/oob_controller_test.go
  internal/controller/suite_test.go
Labels: feature

#95 Clean up minor things
  .github/workflows/auto-merge.yml
  .github/workflows/draft-release.yml
  Dockerfile
  Makefile
Labels: chore

#101 Improve OOB tests
  cmd/main.go
  internal/controller/oob_controller_test.go
  test/macdb.yaml
Labels: chore

#104 Add manual trigger for docker build action
  .github/workflows/publish-docker.yml
Labels: feature

#105 fix missing rbac rules
  config/rbac/role.yaml
  internal/controller/machine_controller.go
Labels: bug

#106 machine object changes detection
  internal/controller/machine_controller.go
Labels: chore

#102 Validate endpoint with a BMC ping
  internal/bmc/bmc.go
  internal/bmc/fake.go
  internal/bmc/ipmi.go
  internal/bmc/redfish.go
  internal/controller/machine_controller.go
  internal/controller/oob_controller.go
Labels: enhancement

#108 fix machine to machineApply conversion
  internal/controller/machine_controller.go
Labels: bug

#115 Temporarily disable OOB machine conditions
  internal/controller/oob_controller.go
Labels: chore

#116 fix machine apply configuration
  internal/controller/machine_controller.go
Labels: bug

#117 fix missing flag in params parsed from command line
  cmd/main.go
Labels: bug

#118 Enable inventory controller
  cmd/main.go
  internal/controller/suite_test.go
Labels: bug

#119 Machine classification
  PROJECT
  api/v1alpha1/aggregate_types.go
  api/v1alpha1/aggregation_results.go
  api/v1alpha1/common.go
  api/v1alpha1/constraint_types.go
  api/v1alpha1/constraintval_type.go
  api/v1alpha1/funcs.go
  api/v1alpha1/inventory_types.go
  api/v1alpha1/jsonpath_types.go
  api/v1alpha1/machine_types.go
  api/v1alpha1/size_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  client/applyconfiguration/api/v1alpha1/aggregate.go
  client/applyconfiguration/api/v1alpha1/aggregateitem.go
  client/applyconfiguration/api/v1alpha1/aggregatespec.go
  client/applyconfiguration/api/v1alpha1/constraintspec.go
  client/applyconfiguration/api/v1alpha1/inventorystatus.go
  client/applyconfiguration/api/v1alpha1/size.go
  client/applyconfiguration/api/v1alpha1/sizespec.go
  client/applyconfiguration/internal/internal.go
  client/applyconfiguration/utils.go
  client/openapi/zz_generated.openapi.go
  cmd/main.go
  config/crd/bases/metal.ironcore.dev_aggregates.yaml
  config/crd/bases/metal.ironcore.dev_inventories.yaml
  config/crd/bases/metal.ironcore.dev_machines.yaml
  config/crd/bases/metal.ironcore.dev_sizes.yaml
  config/crd/kustomization.yaml
  config/rbac/role.yaml
  internal/controller/aggregate_controller.go
  internal/controller/inventory_controller.go
  internal/controller/size_controller.go
Labels: feature

#120 fix manager rbac for inventories
  config/rbac/role.yaml
  internal/controller/aggregate_controller.go
  internal/controller/inventory_controller.go
Labels: bug

#122 fix infinite reconciliation caused by applying empty machine.status
  internal/controller/machine_controller.go
Labels: bug

#123 ensure machine power status is Off before making it available
  internal/controller/machine_controller.go
Labels: enhancement

#124 dummy implementation of machine cleanup controller
  cmd/main.go
  internal/controller/cleanup_controller.go
  internal/controller/machineclaim_controller.go
Labels: feature

#125 licenses and const renaming
  api/v1alpha1/aggregate_types.go
  api/v1alpha1/aggregation_results.go
  api/v1alpha1/constraint_types.go
  api/v1alpha1/constraintval_type.go
  api/v1alpha1/funcs.go
  api/v1alpha1/jsonpath_types.go
  api/v1alpha1/size_types.go
  client/openapi/zz_generated.openapi.go
  internal/controller/aggregate_controller.go
  internal/controller/cleanup_controller.go
  internal/controller/inventory_controller.go
  internal/controller/machine_controller.go
  internal/controller/size_controller.go
Labels: chore

#127 power off the machine after cleanup is done
  internal/controller/cleanup_controller.go
  internal/controller/inventory_controller.go
Labels: enhancement

#133 create boot configuration for inventory
  cmd/main.go
  config/crd/bases/metal.ironcore.dev_bootconfigurations.yaml
  config/crd/kustomization.yaml
  internal/controller/machine_controller.go
  internal/controller/suite_test.go
Labels: feature

#135 add boot configuration reference to machine spec
  api/v1alpha1/bootconfiguration_types.go
  api/v1alpha1/machine_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  client/applyconfiguration/api/v1alpha1/machinespec.go
  client/applyconfiguration/internal/internal.go
  client/openapi/zz_generated.openapi.go
  cmd/main.go
  config/crd/bases/metal.ironcore.dev_bootconfigurations.yaml
  config/crd/bases/metal.ironcore.dev_machines.yaml
  config/rbac/bootconfiguration_editor_role.yaml
  config/rbac/bootconfiguration_viewer_role.yaml
  config/rbac/role.yaml
  internal/controller/inventory_controller.go
  internal/controller/machine_controller.go
  internal/controller/suite_test.go
Labels: enhancement

#136 update bootConfiguration api
  api/v1alpha1/bootconfiguration_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  client/applyconfiguration/api/v1alpha1/bootconfigurationspec.go
  client/applyconfiguration/internal/internal.go
  client/openapi/zz_generated.openapi.go
  cmd/main.go
  config/crd/bases/metal.ironcore.dev_bootconfigurations.yaml
  internal/controller/machine_controller.go
  internal/controller/suite_test.go
Labels: enhancement

#138 update inventory status with aggregated values
  cmd/main.go
  config/rbac/aggregate_editor_role.yaml
  config/rbac/aggregate_viewer_role.yaml
  internal/controller/aggregate_controller.go
  internal/controller/inventory_controller.go
  internal/controller/suite_test.go
Labels: enhancement
